site_name: Learning Base
theme:
  name: readthedocs
  custom_dir: custom_theme/
nav:
  - Home: index.md
  - SharePoint: 
    - introduction: sharepoint/index.md
copyright: copyright@ 2022 xiong, All right reserved.

