site_name: Learning Base
theme:
  name: material
  custom_dir: custom_theme/
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
nav:
  - Home: index.md
  - Microsoft:
    - SharePoint: 
      - introduction: microsoft/sharepoint/index.md
    - Power Platform:
      - PowerApps: microsoft/powerplatform/powerapps/index.md
  - Adobe:
    - AEM:
      - Sites: adobe/aem/sites/index.md
markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
copyright: copyright@ 2022 xiong, All right reserved


