site_name: Learning Base
theme:
  name: material
  custom_dir: custom_theme/
nav:
  - Home: index.md
  - SharePoint: 
    - introduction: sharepoint/index.md
markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
copyright: copyright@ 2022 xiong, All right reserved


